// AUTO-GENERATED by scripts/gen-sample-sources.mjs — DO NOT EDIT BY HAND.
// Explicit ?raw imports of every Codebase/Microservice/samples/**/*.cpp, replacing the
// Vite-only import.meta.glob so the same source builds under Next.js/webpack too (D89).
// Re-run: node scripts/gen-sample-sources.mjs

import s0 from '../../../../Microservice/samples/abstract_factory/gui_factory.cpp?raw';
import s1 from '../../../../Microservice/samples/adapter/payment_gateway_adapter.cpp?raw';
import s2 from '../../../../Microservice/samples/bridge/shape_renderer.cpp?raw';
import s3 from '../../../../Microservice/samples/builder/http_request_builder.cpp?raw';
import s4 from '../../../../Microservice/samples/chain_of_responsibility/handler_chain.cpp?raw';
import s5 from '../../../../Microservice/samples/command/command_undo.cpp?raw';
import s6 from '../../../../Microservice/samples/composite/graphic_tree.cpp?raw';
import s7 from '../../../../Microservice/samples/decorator/coffee_decorator.cpp?raw';
import s8 from '../../../../Microservice/samples/edge_cases/composite_no_pattern.cpp?raw';
import s9 from '../../../../Microservice/samples/edge_cases/fake_singleton_friend.cpp?raw';
import s10 from '../../../../Microservice/samples/edge_cases/hidden_singleton.cpp?raw';
import s11 from '../../../../Microservice/samples/edge_cases/intentionally_clean_dto.cpp?raw';
import s12 from '../../../../Microservice/samples/edge_cases/multimethod_no_pattern.cpp?raw';
import s13 from '../../../../Microservice/samples/edge_cases/proxy_shaped_dto.cpp?raw';
import s14 from '../../../../Microservice/samples/facade/computer_facade.cpp?raw';
import s15 from '../../../../Microservice/samples/factory/shape_factory.cpp?raw';
import s16 from '../../../../Microservice/samples/flyweight/glyph_factory.cpp?raw';
import s17 from '../../../../Microservice/samples/interpreter/expression_interpreter.cpp?raw';
import s18 from '../../../../Microservice/samples/iterator/list_iterator.cpp?raw';
import s19 from '../../../../Microservice/samples/mediator/mediator_notify.cpp?raw';
import s20 from '../../../../Microservice/samples/memento/editor_memento.cpp?raw';
import s21 from '../../../../Microservice/samples/method_chaining/query_predicate.cpp?raw';
import s22 from '../../../../Microservice/samples/mixed/mixed_classes.cpp?raw';
import s23 from '../../../../Microservice/samples/negative/plain_class_no_pattern.cpp?raw';
import s24 from '../../../../Microservice/samples/negative/plain_widget.cpp?raw';
import s25 from '../../../../Microservice/samples/observer/observer_subject.cpp?raw';
import s26 from '../../../../Microservice/samples/pimpl/pimpl_basic.cpp?raw';
import s27 from '../../../../Microservice/samples/prototype/shape_clone.cpp?raw';
import s28 from '../../../../Microservice/samples/singleton/config_registry.cpp?raw';
import s29 from '../../../../Microservice/samples/state/state_machine.cpp?raw';
import s30 from '../../../../Microservice/samples/strategy/strategy_basic.cpp?raw';
import s31 from '../../../../Microservice/samples/strategy/strategy_with_pimpl.cpp?raw';
import s32 from '../../../../Microservice/samples/template_method/report_generator.cpp?raw';
import s33 from '../../../../Microservice/samples/usages/usages_adapter_trace.cpp?raw';
import s34 from '../../../../Microservice/samples/usages/usages_basic.cpp?raw';
import s35 from '../../../../Microservice/samples/usages/usages_smart_pointers.cpp?raw';
import s36 from '../../../../Microservice/samples/visitor/visitor_shapes.cpp?raw';
import s37 from '../../../../Microservice/samples/wrapping/logging_proxy.cpp?raw';

// Keyed by the original glob path so SamplePickerModal.buildSamples() is unchanged.
export const RAW_SAMPLES: Record<string, string> = {
  '../../../../Microservice/samples/abstract_factory/gui_factory.cpp': s0,
  '../../../../Microservice/samples/adapter/payment_gateway_adapter.cpp': s1,
  '../../../../Microservice/samples/bridge/shape_renderer.cpp': s2,
  '../../../../Microservice/samples/builder/http_request_builder.cpp': s3,
  '../../../../Microservice/samples/chain_of_responsibility/handler_chain.cpp': s4,
  '../../../../Microservice/samples/command/command_undo.cpp': s5,
  '../../../../Microservice/samples/composite/graphic_tree.cpp': s6,
  '../../../../Microservice/samples/decorator/coffee_decorator.cpp': s7,
  '../../../../Microservice/samples/edge_cases/composite_no_pattern.cpp': s8,
  '../../../../Microservice/samples/edge_cases/fake_singleton_friend.cpp': s9,
  '../../../../Microservice/samples/edge_cases/hidden_singleton.cpp': s10,
  '../../../../Microservice/samples/edge_cases/intentionally_clean_dto.cpp': s11,
  '../../../../Microservice/samples/edge_cases/multimethod_no_pattern.cpp': s12,
  '../../../../Microservice/samples/edge_cases/proxy_shaped_dto.cpp': s13,
  '../../../../Microservice/samples/facade/computer_facade.cpp': s14,
  '../../../../Microservice/samples/factory/shape_factory.cpp': s15,
  '../../../../Microservice/samples/flyweight/glyph_factory.cpp': s16,
  '../../../../Microservice/samples/interpreter/expression_interpreter.cpp': s17,
  '../../../../Microservice/samples/iterator/list_iterator.cpp': s18,
  '../../../../Microservice/samples/mediator/mediator_notify.cpp': s19,
  '../../../../Microservice/samples/memento/editor_memento.cpp': s20,
  '../../../../Microservice/samples/method_chaining/query_predicate.cpp': s21,
  '../../../../Microservice/samples/mixed/mixed_classes.cpp': s22,
  '../../../../Microservice/samples/negative/plain_class_no_pattern.cpp': s23,
  '../../../../Microservice/samples/negative/plain_widget.cpp': s24,
  '../../../../Microservice/samples/observer/observer_subject.cpp': s25,
  '../../../../Microservice/samples/pimpl/pimpl_basic.cpp': s26,
  '../../../../Microservice/samples/prototype/shape_clone.cpp': s27,
  '../../../../Microservice/samples/singleton/config_registry.cpp': s28,
  '../../../../Microservice/samples/state/state_machine.cpp': s29,
  '../../../../Microservice/samples/strategy/strategy_basic.cpp': s30,
  '../../../../Microservice/samples/strategy/strategy_with_pimpl.cpp': s31,
  '../../../../Microservice/samples/template_method/report_generator.cpp': s32,
  '../../../../Microservice/samples/usages/usages_adapter_trace.cpp': s33,
  '../../../../Microservice/samples/usages/usages_basic.cpp': s34,
  '../../../../Microservice/samples/usages/usages_smart_pointers.cpp': s35,
  '../../../../Microservice/samples/visitor/visitor_shapes.cpp': s36,
  '../../../../Microservice/samples/wrapping/logging_proxy.cpp': s37,
};
