// ============================================================
// CodiNeo — Mock API Data
// Stub responses for all pages
// ============================================================

export const MOCK_DATA = {
    dashboard: {
        language: 'C++',
        mode: 'Static analysis',
        safety: 'Virtual AST isolation',
        lastRunStatus: 'Conformant',
        filesAnalyzed: 245,
        violationsFound: 0,
    },

    analysisConfig: {
        language: 'C++',
        files: 5,
        source: 'monolithic',
        target: 'mvc',
        dirtyBit: 'Enabled',
        virtualAST: 'Enabled',
    },

    result: {
        id: 1,
        projectName: 'MyProject-v2',
        status: 'non-conformant',
        completedAt: '2026-02-23 at 14:30',
        structuralViolations: 8,
        semanticAlignment: 87,
        memoryEfficiency: 92,
    },

    diff: {
        id: 1,
        file: 'src/core/engine.cpp',
        original: [
            'class Engine {',
            '  private:',
            '    Database* db;',
            '    Config* config;',
            '    Logger* logger;',
            '',
            '  public:',
            '    Engine() {',
            '      db = new Database();',
            '      config = new Config();',
            '      logger = new Logger();',
            '    }',
            '',
            '    void process() {',
            '      db->query();',
            '    }',
            '',
            '    ~Engine() {',
            '      delete db;',
            '      delete config;',
            '      delete logger;',
            '    }',
            '};',
        ],
        transformed: [
            'class Engine {',
            '  private:',
            '    std::unique_ptr<Database> db;',
            '    std::shared_ptr<Config> config;',
            '    std::shared_ptr<Logger> logger;',
            '',
            '  public:',
            '    Engine(',
            '      std::unique_ptr<Database> db_ptr,',
            '      std::shared_ptr<Config> cfg,',
            '      std::shared_ptr<Logger> log',
            '    ) : db(std::move(db_ptr)),',
            '        config(cfg),',
            '        logger(log) {}',
            '',
            '    void process() {',
            '      db->query();',
            '    }',
            '};',
        ],
        deletedLines: [2, 3, 4, 8, 9, 10, 11, 17, 18, 19, 20],
        addedLines: [2, 3, 4, 8, 9, 10, 11, 12, 13, 14],
    },

    fixes: [
        {
            id: 1,
            num: 1,
            category: 'RAII Conformance',
            title: 'Replace raw pointer with std::unique_ptr<Database>',
            file: 'src/core/engine.cpp',
            line: 3,
            confidence: 98,
        },
        {
            id: 2,
            num: 2,
            category: 'RAII Conformance',
            title: 'Replace raw pointer with std::shared_ptr<Config>',
            file: 'src/core/engine.cpp',
            line: 4,
            confidence: 97,
        },
        {
            id: 3,
            num: 3,
            category: 'Dependency Injection',
            title: 'Inject dependencies via constructor parameters',
            file: 'src/core/engine.cpp',
            line: 8,
            confidence: 95,
        },
        {
            id: 4,
            num: 4,
            category: 'Memory Safety',
            title: 'Remove manual destructor — RAII handles cleanup',
            file: 'src/core/engine.cpp',
            line: 17,
            confidence: 99,
        },
        {
            id: 5,
            num: 5,
            category: 'RAII Conformance',
            title: 'Replace raw pointer with std::shared_ptr<Logger>',
            file: 'src/core/engine.cpp',
            line: 5,
            confidence: 96,
        },
        {
            id: 6,
            num: 6,
            category: 'Structural Isolation',
            title: 'Separate Engine construction from database setup',
            file: 'src/core/engine.cpp',
            line: 8,
            confidence: 88,
        },
        {
            id: 7,
            num: 7,
            category: 'Semantic Alignment',
            title: 'Add noexcept specifier to process() method',
            file: 'src/core/engine.cpp',
            line: 14,
            confidence: 85,
        },
        {
            id: 8,
            num: 8,
            category: 'Memory Safety',
            title: 'Use std::move semantics for unique_ptr transfer',
            file: 'src/core/engine.cpp',
            line: 12,
            confidence: 93,
        },
    ],

    checklist: [
        { id: 1, name: 'RAII Compliance', desc: 'Smart pointers replace raw pointers' },
        { id: 2, name: 'Dependency Injection', desc: 'Constructor pattern applied' },
        { id: 3, name: 'Automatic Cleanup', desc: 'Manual destructor removed' },
        { id: 4, name: 'Syntax Verification', desc: 'Code compiles successfully' },
    ],

    download: {
        projectName: 'MyProject-v2',
        filesTransformed: 5,
        violationsFixed: 8,
        pattern: 'MVC',
        memoryModel: 'RAII / Smart Pointers',
        outputFormat: '.zip archive',
    },
};
